// User-facing strings — all text in one place for future i18n
export const STRINGS = {
  app: {
    name: 'SyncDoc',
    tagline: 'The next generation of collaborative writing',
    description:
      'True offline-first collaboration, AI-native editing, cross-document knowledge linking, and sub-100ms sync latency across the globe.',
  },
  auth: {
    loginTitle: 'Welcome back',
    loginSubtitle: 'Sign in to your SyncDoc account',
    signupTitle: 'Create your account',
    signupSubtitle: 'Start collaborating in seconds',
    forgotPassword: 'Forgot your password?',
    rememberMe: 'Remember me',
    signInWithGoogle: 'Continue with Google',
    signInWithGitHub: 'Continue with GitHub',
    signInWithEmail: 'Sign in with email',
    signUpWithEmail: 'Create account',
    magicLink: 'Send magic link',
    magicLinkSent: 'Check your email for the login link',
    orContinueWith: 'or continue with',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    signUp: 'Sign up',
    signIn: 'Sign in',
    sessionExpired: 'Your session has expired. Please sign in again.',
    invalidOAuth: 'Authentication failed. Please try again.',
  },
  onboarding: {
    step1Title: "What's your name?",
    step1Subtitle: "This is how you'll appear to collaborators",
    step2Title: 'Create your workspace',
    step2Subtitle: 'A workspace is where your team collaborates',
    step3Title: 'Start with a template or blank doc?',
    step3Subtitle: 'You can always create more later',
    nameLabel: 'Display name',
    workspaceNameLabel: 'Workspace name',
    workspaceSlugLabel: 'Workspace URL',
    colorLabel: 'Pick your avatar color',
    next: 'Next',
    back: 'Back',
    finish: 'Get started',
  },
  workspace: {
    home: 'Home',
    allDocuments: 'All Documents',
    starred: 'Starred',
    sharedWithMe: 'Shared with me',
    templates: 'Templates',
    trash: 'Trash',
    settings: 'Settings',
    newDocument: 'New Document',
    uploadFile: 'Upload File',
    useTemplate: 'Use Template',
    invitePeople: 'Invite People',
    members: 'members',
    recentDocuments: 'Recent Documents',
    pinnedDocuments: 'Pinned Documents',
    activityFeed: 'Activity',
    noDocuments: 'No documents yet',
    noDocumentsHint: 'Create your first document to get started',
    searchPlaceholder: 'Search documents...',
    trashEmpty: 'Trash is empty',
    trashHint: 'Deleted documents appear here for 30 days',
  },
  editor: {
    untitled: 'Untitled',
    addCover: 'Add cover',
    addIcon: 'Add icon',
    changeCover: 'Change cover',
    removeCover: 'Remove cover',
    wordsLabel: 'words',
    minRead: 'min read',
    saving: 'Saving...',
    saved: 'Saved',
    offline: "You're offline — changes will sync when reconnected",
    reconnecting: 'Reconnecting...',
    connected: 'Connected',
    focusMode: 'Focus mode',
    exitFocusMode: 'Exit focus mode',
    slashPlaceholder: "Type '/' for commands",
    emptyParagraph: "Press '/' for commands, or start typing...",
  },
  share: {
    title: 'Share',
    invitePeople: 'Invite people',
    shareLink: 'Share link',
    publish: 'Publish',
    emailPlaceholder: 'Enter email addresses',
    canView: 'Can view',
    canComment: 'Can comment',
    canEdit: 'Can edit',
    sendInvite: 'Send invite',
    copyLink: 'Copy link',
    linkCopied: 'Link copied!',
    anyoneWithLink: 'Anyone with the link can...',
    noAccess: 'No access',
    disableLink: 'Disable link',
    publishToggle: 'Publish as public page',
    accessRevoked: 'Access to this document has been revoked',
    requestAccess: 'Request access',
    inviteExpired: 'This invite has expired. Request a new one from the document owner.',
    cantInviteSelf: "You can't invite yourself.",
  },
  comments: {
    title: 'Comments',
    addComment: 'Add a comment...',
    reply: 'Reply',
    resolve: 'Resolve',
    unresolve: 'Unresolve',
    resolved: 'Resolved',
    deletedText: 'Deleted text',
    noComments: 'No comments yet',
    loadMore: 'Load more replies',
  },
  history: {
    title: 'Version History',
    viewVersion: 'View this version',
    restoreVersion: 'Restore this version',
    duplicateAsNew: 'Duplicate as new doc',
    saveVersion: 'Save version',
    versionLabel: 'Version label',
    autoSave: 'Auto-save',
    viewingVersion: 'Viewing version from',
    by: 'by',
  },
  ai: {
    title: 'AI Assistant',
    promptPlaceholder: 'Ask AI to write something...',
    improve: 'Improve writing',
    fixGrammar: 'Fix grammar',
    makeShorter: 'Make shorter',
    makeLonger: 'Make longer',
    changeTone: 'Change tone',
    translate: 'Translate',
    explain: 'Explain',
    summarize: 'Summarize',
    customPrompt: 'Custom prompt',
    replaceSelection: 'Replace selection',
    insertBelow: 'Insert below',
    copyToClipboard: 'Copy to clipboard',
    keep: 'Keep',
    discard: 'Discard',
    regenerate: 'Regenerate',
    summarizeDoc: 'Summarize document',
    suggestTitle: 'Suggest title',
    findActionItems: 'Find action items',
    askAboutDoc: 'Ask about this document',
    unavailable: 'AI assistant unavailable. Try again in a moment.',
    rateLimited: "You've used your AI limit for this hour. Upgrade to Pro for unlimited AI.",
    emptyResponse: 'AI returned an empty response',
  },
  export: {
    title: 'Export',
    asPdf: 'Export as PDF',
    asDocx: 'Export as DOCX',
    asMarkdown: 'Export as Markdown',
    asHtml: 'Export as HTML',
    print: 'Print',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    notFound: 'Page not found',
    unauthorized: 'You do not have access to this resource',
    docNotFound: 'This document no longer exists',
    uploadFailed: 'File upload failed. Please try again.',
    unsupportedFormat: 'Unsupported file format. Please upload a .docx, .pdf, .txt, or .md file.',
    fileTooLarge: 'File is too large. Maximum size is 10MB.',
    parseFailed: 'Failed to parse the file. The format may not be supported.',
    scannedPdf:
      'This PDF appears to be scanned. Text extraction may be limited.',
    titleTooLong: 'Title is too long. Truncated to 500 characters.',
    docTooLarge: 'Document is very large. Consider splitting into linked documents.',
    networkError: 'Network error. Check your connection.',
  },
} as const;
